(() => {
  "use strict";
  const SAVE_KEY = "simulador-cofrade-v2"; 
  const SAVES_KEY = "simulador-cofrade-partidas-v1";
  const $ = (id) => document.getElementById(id);
  const money = n => new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(n);
  const dateText = d => new Intl.DateTimeFormat("es-ES",{day:"numeric",month:"long",year:"numeric"}).format(d);
  const esc = s => String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const products = [
    {id:"candelabro",name:"Candelabro de guardabrisas",category:"Candelería",price:1850,quality:82,icon:"🕯️",desc:"Juego de iluminación para el paso. Requiere mantenimiento periódico."},
    {id:"faroles",name:"Pareja de faroles",category:"Enseres",price:720,quality:78,icon:"🏮",desc:"Faroles para acompañamiento procesional."},
    {id:"cruz-guia",name:"Cruz de guía",category:"Enseres",price:2400,quality:90,icon:"✝️",desc:"Pieza principal de apertura de la cofradía."},
    {id:"vara",name:"Juego de varas",category:"Enseres",price:540,quality:70,icon:"⚜️",desc:"Juego de varas para representación y cortejo."},
    {id:"tunicas",name:"Lote de túnicas",category:"Bordados y textiles",price:360,quality:72,icon:"🧵",desc:"Lote de túnicas para ampliar el equipo disponible."},
    {id:"respiraderos",name:"Respiraderos ornamentales",category:"Pasos",price:4600,quality:92,icon:"🪵",desc:"Conjunto ornamental para el paso."},
    {id:"flores",name:"Exorno floral de cultos",category:"Flores y exorno",price:180,quality:80,icon:"💐",desc:"Composición floral para un culto próximo."},
    {id:"limpieza",name:"Kit de conservación",category:"Mantenimiento",price:95,quality:75,icon:"🧽",desc:"Material de limpieza y conservación de enseres."},
    {id:"peana",name:"Peana de altar",category:"Altar e imaginería",price:950,quality:84,icon:"🕯️",desc:"Peana para la preparación de altares."},
    {id:"imagen-dolorosa",name:"Imagen de Dolorosa (talla de taller)",category:"Imaginería",price:18500,quality:96,icon:"🕊️",desc:"Imagen devocional de gran valor patrimonial. Compra de alto coste que requiere una tesorería saneada."},
    {id:"imagen-cristo",name:"Imagen de Cristo (talla de taller)",category:"Imaginería",price:24000,quality:98,icon:"✝️",desc:"Talla de imaginería de alta calidad para un proyecto patrimonial a largo plazo."},
    {id:"imagen-secundaria",name:"Imagen secundaria para misterio",category:"Imaginería",price:6800,quality:88,icon:"🗿",desc:"Imagen secundaria para completar un conjunto escultórico."},
    {id:"angel-altar",name:"Pareja de ángeles de altar",category:"Imaginería",price:1450,quality:82,icon:"👼",desc:"Figuras ornamentales para cultos y altares."},
    {id:"paso-misterio",name:"Estructura de paso de misterio",category:"Pasos",price:14500,quality:94,icon:"🪵",desc:"Estructura de paso para un proyecto de gran envergadura."},
    {id:"palio",name:"Estructura de palio",category:"Pasos",price:19500,quality:95,icon:"🏵️",desc:"Estructura de palio para un proyecto patrimonial de alto coste."},
    {id:"candeleria",name:"Lote de candelería",category:"Candelería",price:1100,quality:77,icon:"🕯️",desc:"Candelería para cultos y montajes."},
    {id:"estandarte",name:"Estandarte bordado",category:"Bordados y textiles",price:3200,quality:95,icon:"🏵️",desc:"Estandarte de calidad alta para el cortejo."},
    {id:"carpinteria",name:"Material de carpintería",category:"Mantenimiento",price:140,quality:70,icon:"🪚",desc:"Material básico para pequeñas reparaciones."},
    {id:"cristo-basico",name:"Imagen de Cristo de serie",category:"Imaginería",price:4200,quality:68,icon:"✝️",desc:"Talla de catálogo de nivel inicial, adecuada para una hermandad que empieza."},
    {id:"dolorosa-media",name:"Imagen de Dolorosa de taller",category:"Imaginería",price:11200,quality:85,icon:"🕊️",desc:"Talla de taller de nivel medio, con acabados y policromía cuidados."},
    {id:"misterio-completo",name:"Conjunto de misterio (4 figuras)",category:"Imaginería",price:28500,quality:91,icon:"🗿",desc:"Conjunto escultórico de nivel alto para completar una escena procesional."},
    {id:"apostoles-premium",name:"Conjunto de apóstoles (6 figuras)",category:"Imaginería",price:39000,quality:97,icon:"🗿",desc:"Conjunto de gran calidad artística; inversión patrimonial de largo recorrido."},
    {id:"paso-sencillo",name:"Paso de misterio sencillo",category:"Pasos",price:7800,quality:72,icon:"🪵",desc:"Estructura funcional de nivel básico, ampliable con el tiempo."},
    {id:"paso-talla-media",name:"Paso tallado de nivel medio",category:"Pasos",price:22000,quality:88,icon:"🏵️",desc:"Paso con talla ornamental y mejores acabados."},
    {id:"paso-talla-premium",name:"Paso de misterio de alta talla",category:"Pasos",price:48000,quality:98,icon:"🪵",desc:"Paso de gran categoría artística y coste de mantenimiento elevado."},
    {id:"palio-basico",name:"Juego de varales de palio",category:"Pasos",price:6200,quality:74,icon:"🏵️",desc:"Juego básico de varales para iniciar un proyecto de palio."},
    {id:"techo-palio",name:"Techo de palio bordado",category:"Bordados y textiles",price:27500,quality:93,icon:"🧵",desc:"Techo bordado de nivel alto para un palio de gran presencia."},
    {id:"manto-salida",name:"Manto de salida bordado",category:"Bordados y textiles",price:36000,quality:97,icon:"🧵",desc:"Pieza de gran categoría, requiere conservación especializada."},
    {id:"cruz-guia-premium",name:"Cruz de guía de orfebrería",category:"Enseres",price:7800,quality:96,icon:"✝️",desc:"Cruz de guía de orfebrería artística de nivel premium."},
    {id:"juego-faroles-premium",name:"Juego de faroles de orfebrería",category:"Enseres",price:4900,quality:93,icon:"🏮",desc:"Pareja de faroles con acabados de alta calidad."},
    {id:"candeleria-completa",name:"Candelería completa de palio",category:"Candelería",price:8600,quality:91,icon:"🕯️",desc:"Lote amplio para un montaje de palio más completo."},
    {id:"bandera-bordada",name:"Bandera corporativa bordada",category:"Bordados y textiles",price:1850,quality:83,icon:"🏳️",desc:"Bandera bordada de nivel intermedio para el cortejo."}
  ];
  products.forEach(p=>{p.tier=p.price<1000?"Básico":p.price<8000?"Intermedio":p.price<20000?"Avanzado":"Premium";});
  const eventTemplates = [
    {title:"Donativo inesperado",desc:"Una familia de la feligresía quiere colaborar con la hermandad.",choices:[{label:"Agradecer y aceptar",text:"Se registra el donativo.",money:120,rep:2},{label:"Reservarlo para un proyecto",text:"El donativo queda comprometido para el patrimonio.",money:40,rep:1}]},
    {title:"Incidencia en un enser",desc:"Durante una revisión se detecta que una pieza metálica necesita atención.",choices:[{label:"Repararlo ahora",text:"La pieza queda atendida.",money:-180,rep:2},{label:"Aplazar la reparación",text:"Se ahorra ahora, pero el estado del enser empeora.",money:0,rep:-3,wear:8}]},
    {title:"Proveedor con una oferta",desc:"Un proveedor ofrece material de conservación a precio reducido durante unos días.",choices:[{label:"Comprar el lote",text:"Se adquiere material para la priostía.",money:-95,rep:2,add:"limpieza"},{label:"No comprar por ahora",text:"La tesorería conserva el saldo.",money:0,rep:0}]},
    {title:"Cuotas pendientes",desc:"Secretaría informa de varias cuotas que todavía no se han abonado.",choices:[{label:"Enviar recordatorio cordial",text:"Se recupera parte de las cuotas.",money:70,rep:1},{label:"Esperar al próximo mes",text:"No se realiza ninguna gestión.",money:0,rep:0}]},
    {title:"Preparación de un culto",desc:"Se acerca un culto y la priostía necesita organizar los enseres y el altar.",choices:[{label:"Montaje extraordinario",text:"Un montaje cuidado deja una gran impresión, pero cuesta más.",money:-450,rep:8},{label:"Montaje completo",text:"El culto queda bien preparado.",money:-180,rep:4},{label:"Preparación básica",text:"Se cumple con lo imprescindible.",money:-35,rep:1}]},
    {title:"Propuesta de restauración",desc:"Un taller especializado informa de daños en una pieza patrimonial. La junta debe elegir el alcance de la intervención.",choices:[{label:"Restauración integral",text:"La pieza queda restaurada con una intervención completa.",money:-1800,rep:10},{label:"Conservación preventiva",text:"Se estabiliza la pieza y se evita que empeore.",money:-620,rep:5},{label:"Intervención mínima",text:"Se atiende solo lo urgente.",money:-180,rep:1}]},
    {title:"Proyecto de nueva imagen",desc:"La hermandad recibe propuestas de talleres de imaginería para un futuro proyecto. El coste depende del nivel elegido.",choices:[{label:"Encargar talla de primera categoría",text:"Se reserva un proyecto artístico de alto nivel.",money:-4500,rep:12},{label:"Encargar una talla de nivel intermedio",text:"Se inicia un proyecto de calidad media.",money:-1900,rep:6},{label:"Solicitar estudio previo",text:"Se paga una valoración inicial antes de comprometerse.",money:-350,rep:2}]},
    {title:"Propuesta de un hermano",desc:"Un hermano propone organizar una jornada de convivencia y colaboración.",choices:[{label:"Organizar la jornada",text:"La convivencia refuerza el compromiso de los hermanos.",money:-80,rep:4},{label:"Aplazar la propuesta",text:"Se revisará más adelante.",money:0,rep:-1}]},
    {title:"Factura del almacén",desc:"Llega una factura de mantenimiento de las instalaciones.",choices:[{label:"Pagar la factura",text:"La cuenta queda al día.",money:-240,rep:1},{label:"Solicitar un aplazamiento",text:"Se conserva el dinero por ahora, pero baja la confianza.",money:0,rep:-2}]},
    {title:"Material para la Cuaresma",desc:"Se aproxima la Cuaresma y conviene revisar las existencias de cera y limpieza.",choices:[{label:"Comprar material",text:"La hermandad se prepara con tiempo.",money:-160,rep:3},{label:"Aprovechar existencias",text:"No se realiza gasto adicional.",money:0,rep:0}]},
    {title:"Reconocimiento de la feligresía",desc:"La parroquia destaca la implicación de la hermandad en la vida del barrio.",choices:[{label:"Organizar una jornada abierta",text:"La convivencia mejora la imagen pública, aunque requiere organización.",money:-120,rep:7},{label:"Agradecer el reconocimiento",text:"Se mantiene una relación cordial sin gasto adicional.",money:0,rep:3},{label:"No darle importancia",text:"La oportunidad de acercamiento se pierde.",money:0,rep:-2}]},
    {title:"Queja por falta de información",desc:"Varios hermanos comentan que los avisos de cultos y reuniones llegaron tarde.",choices:[{label:"Enviar comunicado y disculpa",text:"La junta reconoce el fallo y mejora la comunicación.",money:-45,rep:5},{label:"Actualizar solo el tablón",text:"Se corrige parte del problema.",money:0,rep:1},{label:"Ignorar las quejas",text:"La falta de respuesta genera malestar.",money:0,rep:-6}]},
    {title:"Donación de un antiguo enser",desc:"Una familia ofrece un enser antiguo que perteneció a sus mayores.",choices:[{label:"Aceptar y catalogar",text:"El patrimonio crece y la familia agradece el cuidado del objeto.",money:0,rep:5,add:"estandarte"},{label:"Aceptar tras revisar su estado",text:"Se realiza una valoración antes de incorporarlo.",money:-90,rep:3},{label:"Rechazar sin explicación",text:"La familia se siente poco escuchada.",money:0,rep:-4}]},
    {title:"Incidencia durante un ensayo",desc:"Un cambio de última hora provoca retrasos y comentarios entre los participantes.",choices:[{label:"Reorganizar y pedir disculpas",text:"La respuesta responsable reduce el malestar.",money:-70,rep:4},{label:"Seguir con el plan original",text:"Se mantiene el plan, aunque quedan molestias.",money:0,rep:-1},{label:"Culpar públicamente a los participantes",text:"La tensión aumenta y la confianza cae.",money:0,rep:-7}]},
    {title:"Oferta de un taller de imaginería",desc:"Un taller ofrece una pieza de catálogo a buen precio, pero la tesorería debe valorar la inversión.",choices:[{label:"Comprar imagen de nivel básico",text:"Se incorpora una talla sencilla al patrimonio.",money:-4200,rep:2,add:"cristo-basico"},{label:"Pedir presupuesto detallado",text:"Se estudia la propuesta sin comprometer fondos.",money:-80,rep:1},{label:"Comprar sin revisar las cuentas",text:"La decisión precipitada genera críticas por la gestión económica.",money:0,rep:-5}]},
    {title:"Campaña solidaria del barrio",desc:"Una asociación vecinal propone colaborar en una recogida de alimentos.",choices:[{label:"Colaborar con organización y difusión",text:"La hermandad refuerza su compromiso social.",money:-250,rep:8},{label:"Aportar una cantidad modesta",text:"La hermandad participa dentro de sus posibilidades.",money:-75,rep:4},{label:"Declinar de malas formas",text:"La respuesta perjudica la relación con el barrio.",money:0,rep:-5}]},
    {title:"Desacuerdo en la junta",desc:"La junta está dividida sobre una compra importante para el patrimonio.",choices:[{label:"Convocar reunión y votar",text:"La decisión se toma de forma transparente.",money:-30,rep:4},{label:"Aplazar para estudiar las cuentas",text:"Se gana tiempo y se evita una decisión precipitada.",money:0,rep:2},{label:"Imponer la decisión sin escuchar",text:"La falta de diálogo provoca desconfianza.",money:0,rep:-6}]}
  ];
  const activities = [
    {name:"Limpieza de candelería",kind:"Priostía",cost:25,rep:2,season:"cuaresma"},
    {name:"Revisión de túnicas y equipos",kind:"Secretaría",cost:10,rep:2,season:"cuaresma"},
    {name:"Preparación del altar de cultos",kind:"Priostía",cost:55,rep:3,season:"cuaresma"},
    {name:"Revisión de horarios e itinerario",kind:"Organización",cost:0,rep:2,season:"cuaresma"},
    {name:"Inventario de enseres",kind:"Priostía",cost:0,rep:1,season:"general"},
    {name:"Reunión de junta de gobierno",kind:"Gobierno",cost:0,rep:1,season:"general"},
    {name:"Jornada de convivencia",kind:"Hermanos",cost:75,rep:3,season:"general"},
    {name:"Revisión de facturas",kind:"Mayordomía",cost:0,rep:1,season:"general"},
    {name:"Ensayo de organización del cortejo",kind:"Organización",cost:30,rep:2,season:"cuaresma"}
  ];
  const today = new Date(); today.setHours(12,0,0,0);
  let state = null, pendingEvent = null, currentCase = null, cleanTask = null, playTimer = null, resumePlaybackAfterModal = false, currentMonthlyReport = null;
  function freshState(){
    return {date:today.toISOString(),balance:12000,reputation:65,difficulty:"equilibrada",lastElectionMonth:today.getFullYear()*12+today.getMonth(),electionDue:false,brothers:[
      {name:"Manuel Rodríguez",role:"Diputado de tramo",status:"Activo"},
      {name:"Carmen López",role:"Secretaría",status:"Activa"},
      {name:"Antonio García",role:"Hermano",status:"Activo"},
      {name:"María Fernández",role:"Priostía",status:"Activa"}
    ],inventory:[
      {id:"libro-reglas",name:"Libro de reglas",category:"Enseres",icon:"📕",quality:90,condition:92,bought:"Patrimonio inicial",price:0},
      {id:"varas-iniciales",name:"Varas de representación",category:"Enseres",icon:"⚜️",quality:75,condition:80,bought:"Patrimonio inicial",price:0},
      {id:"candeleria-inicial",name:"Candelería de cultos",category:"Candelería",icon:"🕯️",quality:78,condition:85,bought:"Patrimonio inicial",price:0}
    ],church:{name:"Iglesia asignada",type:"assigned",owned:false},house:{type:"none",name:"Sin casa hermandad",level:0},procession:{route:"Iglesia de salida → calles del barrio → plaza principal → regreso a la iglesia",stops:"",startTime:"16:00",returnTime:"01:00",distance:6,plannedYear:null,planned:false},transactions:[{concept:"Tesorería inicial",amount:12000,type:"saldo",date:today.toISOString()}],events:[],eventHistory:[],eventCooldowns:{},activity:["Se ha iniciado una nueva partida."],calendar:[],requests:[],seenRequests:[],lastEventDay:"",lastManualEventDay:"",lastEconomyMonth:"",lastMonthlyReportKey:"",dayCount:0,playing:false,saveId:"",gameName:"Hermandad del Consuelo"};
  }
  function getSaves(){try{const raw=localStorage.getItem(SAVES_KEY);return raw?JSON.parse(raw):[];}catch(e){return [];}}
  function putSaves(list){localStorage.setItem(SAVES_KEY,JSON.stringify(list));}
  function summarizeState(s){const d=new Date(s.date);return {id:s.saveId||("partida-"+Date.now()),name:s.gameName||"Hermandad del Consuelo",date:s.date,balance:s.balance,brothers:(s.brothers||[]).length,reputation:s.reputation||0,inventory:(s.inventory||[]).length,updatedAt:new Date().toISOString(),data:s};}
  function saveCurrentSlot(){if(!state)return;const list=getSaves();if(!state.saveId)state.saveId="partida-"+Date.now()+"-"+Math.random().toString(36).slice(2,7);if(!state.gameName)state.gameName="Hermandad del Consuelo";const item=summarizeState(state);const idx=list.findIndex(x=>x.id===state.saveId);if(idx>=0)list[idx]=item;else list.unshift(item);putSaves(list);localStorage.setItem(SAVE_KEY,JSON.stringify(state));renderSavedGames();}
  function migrateOldSave(){try{const old=localStorage.getItem(SAVE_KEY);const list=getSaves();if(old&&!list.length){const s=JSON.parse(old);if(s&&s.date){s.saveId="partida-migrada-"+Date.now();s.gameName=s.gameName||"Hermandad del Consuelo";const item=summarizeState(s);item.id=s.saveId;putSaves([item]);}}}catch(e){}}
  function renderSavedGames(){const host=$("lista-partidas");if(!host)return;const list=getSaves().sort((a,b)=>new Date(b.updatedAt||b.date)-new Date(a.updatedAt||a.date));if(!list.length){host.innerHTML='<div class="saved-games-empty">Todavía no tienes partidas guardadas. Pulsa «Nueva partida» para comenzar.</div>';return;}host.innerHTML=list.map(s=>`<article class="saved-game-card"><h4>${esc(s.name||"Hermandad del Consuelo")}</h4><div class="saved-game-meta"><span>Fecha de juego<br><strong>${esc(dateText(new Date(s.date)))}</strong></span><span>Tesorería<br><strong>${money(Number(s.balance)||0)}</strong></span><span>Hermanos<br><strong>${Number(s.brothers)||0}</strong></span><span>Patrimonio<br><strong>${Number(s.inventory)||0} bienes</strong></span></div><div class="saved-game-actions"><button class="btn primary" data-load-save="${esc(s.id)}">Continuar</button><button class="btn ghost" data-delete-save="${esc(s.id)}">Eliminar</button></div></article>`).join("");}
  function loadSaveById(id){const s=getSaves().find(x=>x.id===id);if(!s)return toast("No se encuentra esa partida.");state=JSON.parse(JSON.stringify(s.data));ensureStateDefaults();currentCase=(state.requests||[]).find(r=>["Pendiente","Pendiente de subsanación","Subsanada — pendiente de revisión"].includes(r.status))||null;state.saveId=s.id;state.playing=false;cleanTask=null;if(playTimer){clearInterval(playTimer);playTimer=null;}localStorage.setItem(SAVE_KEY,JSON.stringify(state));showScreen("juego");renderAll();section("resumen");updatePlayButton();toast("Partida cargada.");}
  function deleteSaveById(id){const s=getSaves().find(x=>x.id===id);if(!s)return;if(!confirm(`¿Eliminar la partida «${s.name||"Hermandad del Consuelo"}»? Esta acción no se puede deshacer.`))return;putSaves(getSaves().filter(x=>x.id!==id));if(state&&state.saveId===id){state=null;if(playTimer){clearInterval(playTimer);playTimer=null;}showScreen("inicio");}renderSavedGames();toast("Partida eliminada.");}
  function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));if(state)saveCurrentSlot();$("btn-continuar")&&($("btn-continuar").disabled=false);$("estado-guardado").textContent="Tus partidas se guardan en este dispositivo.";}catch(e){toast("No se pudo guardar la partida.");}}
  function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return false;state=JSON.parse(raw);ensureStateDefaults();return !!state.date;}catch(e){return false;}}
  function ensureStateDefaults(){if(!state)return;state.events=Array.isArray(state.events)?state.events:[];state.eventHistory=Array.isArray(state.eventHistory)?state.eventHistory:[];state.eventCooldowns=state.eventCooldowns||{};state.activity=Array.isArray(state.activity)?state.activity:[];state.transactions=Array.isArray(state.transactions)?state.transactions:[];state.requests=Array.isArray(state.requests)?state.requests:[];state.difficulty=state.difficulty||"equilibrada";state.lastManualEventDay=state.lastManualEventDay||"";if(typeof state.lastElectionMonth!=="number"){const d=new Date(state.date);state.lastElectionMonth=d.getFullYear()*12+d.getMonth();}if(typeof state.electionDue!=="boolean")state.electionDue=false;}
  function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2800);}
  function log(message){state.activity.unshift({date:state.date,text:message});state.activity=state.activity.slice(0,12);}
  function addTransaction(concept,amount,type){state.balance=Math.round((state.balance+amount)*100)/100;state.transactions.unshift({concept,amount,type,date:state.date});}
  function showScreen(id){$("pantalla-inicio").classList.toggle("hidden",id!=="inicio");$("pantalla-juego").classList.toggle("hidden",id!=="juego");}
  function section(name){document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.section===name));document.querySelectorAll(".section").forEach(s=>s.classList.toggle("active",s.id==="section-"+name));renderSection(name);}
  function phase(d){const easter=easterDate(d.getFullYear()), ash=new Date(easter);ash.setDate(ash.getDate()-46);const palm=new Date(easter);palm.setDate(palm.getDate()-7);if(d>=ash&&d<easter)return {name:"Cuaresma y Semana Santa",cuaresma:true,description:"Tiempo de cultos, preparación de enseres y organización de la estación de penitencia."};if(d>=easter&&d<new Date(easter.getFullYear(),easter.getMonth()+1,easter.getDate()))return {name:"Pascua",cuaresma:false,description:"Tiempo de balance, agradecimiento y revisión del trabajo realizado."};if(d.getMonth()>=0&&d.getMonth()<=1)return {name:"Preparación del año",cuaresma:false,description:"Organiza el presupuesto y planifica los cultos del año."};return {name:"Tiempo ordinario",cuaresma:false,description:"Mantén el patrimonio, atiende a los hermanos y prepara los próximos compromisos."};}
  function easterDate(year){const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31)-1,day=((h+l-7*m+114)%31)+1;return new Date(year,month,day,12);}
  function stopPlayback(){if(state)state.playing=false;if(playTimer){clearInterval(playTimer);playTimer=null;}updatePlayButton();}
  function startPlayback(){if(!state)return;if(state.events.some(e=>!e.resolved)){toast("Resuelve primero el evento pendiente.");return;}state.playing=true;updatePlayButton();toast("El tiempo avanza automáticamente.");if(playTimer)clearInterval(playTimer);playTimer=setInterval(()=>{if(!state||!state.playing)return;if(state.events.some(e=>!e.resolved)){stopPlayback();return;}advanceDay(true);},2200);}
  function togglePlayback(){if(state.playing)stopPlayback();else startPlayback();save();updatePlayButton();}
  function updatePlayButton(){const b=$("btn-play");if(!b)return;b.textContent=state&&state.playing?"Ⅱ Pausar":"▶ Play";b.classList.toggle("primary",!state||!state.playing);b.classList.toggle("secondary",!!(state&&state.playing));}
  function renderTop(){const d=new Date(state.date);$("nombre-hermandad").textContent=state.gameName||"Hermandad del Consuelo";$("fecha-actual").textContent=dateText(d);$("saldo-cabecera").textContent=money(state.balance);$("total-hermanos").textContent=state.brothers.length;$("reputacion").textContent=state.reputation+"/100";$("saldo-tienda").textContent=money(state.balance)+" disponibles";$("saldo-grande").textContent=money(state.balance);$("eventos-badge").textContent=state.events.filter(e=>!e.resolved).length;}
  function renderSummary(){const p=phase(new Date(state.date));const rep=state.reputation;const repLabel=rep>=85?"Prestigio excelente":rep>=70?"Muy buena imagen":rep>=50?"Reputación estable":rep>=30?"Confianza frágil":"Reputación crítica";$("texto-resumen").textContent=`Hoy es ${dateText(new Date(state.date))}. ${p.description} Reputación: ${repLabel} (${rep}/100). Las decisiones de los eventos pueden mejorar o perjudicar la confianza de los hermanos y del barrio.`;$("resumen-cards").innerHTML=[["Hermanos",state.brothers.length,"Personas censadas"],["Tesorería",money(state.balance),"Saldo disponible"],["Patrimonio",state.inventory.length,"Bienes inventariados"],["Reputación",state.reputation+"/100","Confianza de la comunidad"]].map(c=>`<div class="stat-card"><span>${c[0]}</span><strong>${c[1]}</strong><span>${c[2]}</span></div>`).join("");$("proximos-eventos").innerHTML=state.calendar.slice(0,4).map(a=>`<div class="feed-item"><strong>${esc(a.name)}</strong><small>${esc(a.date)} · ${esc(a.kind)}</small></div>`).join("")||'<p class="muted">No hay compromisos próximos. Avanza el día para generar actividad.</p>';$("actividad-reciente").innerHTML=state.activity.slice(0,5).map(a=>`<div class="feed-item">${esc(typeof a==="string"?a:a.text)}<small>${typeof a==="string"?"Registro":dateText(new Date(a.date))}</small></div>`).join("");}
  function renderEvents(){const day=state.date.slice(0,10);const count=state.events.filter(e=>String(e.date||"").slice(0,10)===day).length;const btn=$("btn-generar-evento");if(btn){btn.disabled=count>=2;btn.title=count>=2?"Ya has alcanzado el límite de dos eventos hoy.":"Puedes buscar novedades, con un máximo de dos eventos por día.";btn.textContent=count>=2?"Límite diario alcanzado":"Buscar novedades";}$("lista-eventos").innerHTML=state.events.filter(e=>!e.resolved).map(e=>`<article class="event-card"><span class="event-meta">${esc(dateText(new Date(e.date)))}</span><h4>${esc(e.title)}</h4><p>${esc(e.desc)}</p><div class="event-actions">${e.choices.map((c,i)=>`<button class="btn ${i===0?"primary":"secondary"}" data-event="${e.id}" data-choice="${i}">${esc(c.label)}</button>`).join("")}</div></article>`).join("")||'<div class="empty">No hay eventos pendientes. Puedes buscar novedades o avanzar un día.</div>';}
  function daysBetween(dateA,dateB){return Math.floor((new Date(dateA).setHours(12,0,0,0)-new Date(dateB).setHours(12,0,0,0))/86400000);}
  function futureIso(dateISO,days){const d=new Date(dateISO);d.setDate(d.getDate()+days);return d.toISOString();}
  function generateEvent(source="auto"){
    if(!state)return false;
    const day=state.date.slice(0,10), count=state.events.filter(e=>String(e.date||"").slice(0,10)===day).length;
    if(count>=2){if(source==="manual")toast("Ya has alcanzado el máximo de 2 eventos en este día.");return false;}
    if(source==="auto"&&state.lastEventDay===day)return false;
    let pool=eventTemplates.filter(t=>!state.eventHistory.slice(-3).includes(t.title));
    pool=pool.filter(t=>!state.eventCooldowns?.[t.title]||new Date(state.eventCooldowns[t.title])<=new Date(state.date));
    if(!pool.length)pool=eventTemplates.filter(t=>!state.eventCooldowns?.[t.title]||new Date(state.eventCooldowns[t.title])<=new Date(state.date));
    if(!pool.length){if(source==="manual")toast("Los eventos de mayor beneficio están en periodo de espera. Avanza unos días.");return false;}
    const t=pool[Math.floor(Math.random()*pool.length)];
    const ev={id:Date.now()+"-"+Math.random().toString(16).slice(2),title:t.title,desc:t.desc,choices:t.choices.map(c=>({...c})),date:state.date,resolved:false};
    state.events.unshift(ev);state.eventHistory.push(t.title);state.eventHistory=state.eventHistory.slice(-12);state.lastEventDay=day;
    if(source==="manual")state.lastManualEventDay=day;
    log("Nuevo evento: "+t.title);
    resumePlaybackAfterModal=!!state.playing;stopPlayback();save();renderEvents();
    setTimeout(()=>{const pending=state&&state.events.find(e=>e.id===ev.id&&!e.resolved);if(pending)showEventModal(pending);},80);
    return true;
  }
  function showEventModal(ev){if(!ev)return;stopPlayback();const choices=ev.choices.map((c,i)=>`<div class="event-level"><div><strong>${esc(c.label)}</strong><p>${esc(c.text)}</p><p>Impacto: <strong>${money(c.money||0)}</strong> · Reputación: ${(c.rep||0)>0?"+":""}${c.rep||0}</p></div><button class="btn ${i===0?"primary":"secondary"}" data-modal-event="${ev.id}" data-modal-choice="${i}">Elegir</button></div>`).join("");
    openModal(`<div class="event-modal-card"><span class="event-meta">EVENTO QUE REQUIERE TU DECISIÓN · ${esc(dateText(new Date(ev.date)))}</span><h3>${esc(ev.title)}</h3><p>${esc(ev.desc)}</p><div class="current-balance-box"><span>TESORERÍA ACTUAL</span><strong>${money(state.balance)}</strong></div><p class="muted">El tiempo está detenido hasta que tomes una decisión. Después continuará si tenías Play activado.</p>${choices}</div>`); }
  function resolveEvent(id,index){const ev=state.events.find(e=>e.id===id);if(!ev||ev.resolved)return;const c=ev.choices[index];if(!c)return;if(c.money<0&&state.balance<Math.abs(c.money)){toast("No hay saldo suficiente para esa decisión.");openModal(`<h3>Saldo insuficiente</h3><p>Tu tesorería actual es ${money(state.balance)} y esta opción cuesta ${money(Math.abs(c.money))}.</p><button class="btn primary" id="volver-evento">Volver al evento</button>`);$("volver-evento").onclick=()=>showEventModal(ev);return;}
    if(c.money)addTransaction(ev.title,c.money,c.money>0?"ingreso":"gasto");state.reputation=Math.max(0,Math.min(100,state.reputation+(c.rep||0)));if(c.wear&&state.inventory.length)state.inventory[0].condition=Math.max(0,state.inventory[0].condition-c.wear);if(c.add){const p=products.find(x=>x.id===c.add);if(p&&!state.inventory.some(x=>x.id===p.id))state.inventory.push({...p,condition:p.quality,bought:dateText(new Date(state.date))});}
    const highBenefit=(c.money||0)>=100||(c.rep||0)>=6||!!c.add;if(highBenefit){if(!state.eventCooldowns)state.eventCooldowns={};state.eventCooldowns[ev.title]=futureIso(state.date,14);}
    ev.resolved=true;log(ev.title+": "+c.text);save();renderAll();toast(c.text);
    const resume=resumePlaybackAfterModal;resumePlaybackAfterModal=false;if(resume){const nextPending=state.events.find(e=>!e.resolved);if(nextPending){resumePlaybackAfterModal=true;showEventModal(nextPending);}else startPlayback();}
  }
  function showMonthlyReport(report){currentMonthlyReport=report;const rows=(report.activities.length?report.activities.map(a=>`<li>${esc(a)}</li>`).join(""):'<li>Sin incidencias destacadas registradas en el mes.</li>');const election=state.electionDue?`<div class="election-panel"><p class="eyebrow">ELECCIONES DE LA HERMANDAD</p><h4>Renovación de la junta</h4><p>Han pasado seis meses desde el último proceso electoral. Elige la línea de gestión para el siguiente mandato.</p><div class="event-actions"><button class="btn primary" data-election-candidate="continuidad">Continuidad <small>+150 € · +4 reputación</small></button><button class="btn secondary" data-election-candidate="renovacion">Renovación <small>+7 reputación · nuevo apoyo</small></button><button class="btn secondary" data-election-candidate="austeridad">Austeridad <small>+300 € · +2 reputación</small></button></div></div>`:'';
    const result=report.electionResult?`<div class="election-result"><h4>Resultado electoral</h4><p>${esc(report.electionResult)}</p></div>`:'';
    openModal(`<div class="monthly-report"><span class="event-meta">CIERRE MENSUAL · ${esc(report.monthName)}</span><h3>Balance de la hermandad</h3><div class="current-balance-box"><span>SALDO ACTUAL</span><strong>${money(state.balance)}</strong></div><div class="monthly-stats"><div><span>Ingresos del mes anterior</span><strong class="success">+${money(report.income)}</strong></div><div><span>Gastos del mes anterior</span><strong class="danger">−${money(report.expenses)}</strong></div><div><span>Balance neto</span><strong class="${report.net>=0?'success':'danger'}">${report.net>=0?'+':'−'}${money(Math.abs(report.net))}</strong></div><div><span>Nuevos hermanos</span><strong>${report.newBrothers.length}</strong></div></div><h4>Altas de hermanos</h4><p>${report.newBrothers.length?report.newBrothers.map(esc).join(', '):'No se registraron nuevas altas el mes pasado.'}</p><h4>Sucesos del mes</h4><ul class="monthly-activity">${rows}</ul>${election}${result}<div class="event-actions"><button class="btn primary" data-monthly-close>Cerrar balance y continuar</button></div></div>`);
  }
  function resolveElection(candidate){if(!state||!state.electionDue||!currentMonthlyReport)return;const choices={continuidad:{name:"Continuidad",money:150,rep:4,desc:"La hermandad ha respaldado a la junta saliente y recibido nuevos donativos."},renovacion:{name:"Renovación",money:-100,rep:7,desc:"La nueva junta impulsa un cambio de etapa y mejora la confianza de los hermanos."},austeridad:{name:"Austeridad",money:300,rep:2,desc:"La junta prioriza el ahorro y obtiene un pequeño fondo extraordinario."}};const c=choices[candidate];if(!c)return;if(c.money<0&&state.balance<Math.abs(c.money)){toast("No hay saldo suficiente para esta transición.");return;}if(c.money)addTransaction("Resultado de elecciones: "+c.name,c.money,c.money>0?"ingreso":"gasto");state.reputation=Math.max(0,Math.min(100,state.reputation+c.rep));if(candidate==="renovacion"){const helpers=["Diputado de gobierno","Secretaría adjunta","Mayordomía adjunta"];state.brothers.push({name:randomPersonName(),role:helpers[Math.floor(Math.random()*helpers.length)],status:"Activo",joinedAt:state.date});}state.lastElectionMonth=new Date(state.date).getFullYear()*12+new Date(state.date).getMonth();state.electionDue=false;log("Elecciones celebradas: gana la candidatura de "+c.name+".");currentMonthlyReport.electionResult=c.desc;save();renderAll();showMonthlyReport(currentMonthlyReport);}
  function randomPersonName(){const first=["Alejandro","Lucía","Manuel","Carmen","Antonio","María","Francisco","Rocío","José","Esperanza","Daniel","Inmaculada","Pablo","Marta","Álvaro","Macarena","Javier","Elena","Adrián","Claudia"];const last=["García López","Rodríguez Pérez","Fernández Ruiz","Sánchez Romero","Martín Díaz","López Moreno","Pérez Jiménez","Gómez Torres","Ruiz Martín","Moreno Díaz"];let name;do{name=first[Math.floor(Math.random()*first.length)]+" "+last[Math.floor(Math.random()*last.length)];}while(state.brothers.some(b=>b.name===name));return name;}
  function makeRequest(){if(currentCase&&["Pendiente","Pendiente de subsanación","Subsanada — pendiente de revisión"].includes(currentCase.status)){toast("Termina primero el expediente que tienes abierto.");renderRequest();return;}const age=16+Math.floor(Math.random()*65),name=randomPersonName();const complete=Math.random()<0.58;const issues=["La ficha está completa y los datos coinciden.","Falta un campo obligatorio de contacto.","La fecha de nacimiento no coincide con la edad declarada.","Falta aportar un documento requerido por las normas del juego."];const issue=complete?issues[0]:issues[1+Math.floor(Math.random()*(issues.length-1))];currentCase={id:Date.now(),name,age,birthYear:new Date(state.date).getFullYear()-age,contact:"6"+String(Math.floor(10000000+Math.random()*89999999)),requestDate:dateText(new Date(state.date)),issue,status:"Pendiente"};state.requests.unshift(currentCase);save();renderRequest();}
  function renderRequest(){const box=$("expediente-actual");if(!currentCase){box.innerHTML='<div class="empty">No hay ningún expediente abierto. Pulsa «Recibir expediente» para comenzar el minijuego.</div>';return;}let actions='';if(currentCase.status==="Pendiente"){actions=`<button class="btn primary" data-case="accept">Aceptar solicitud</button><button class="btn secondary" data-case="fix">Solicitar subsanación</button><button class="btn ghost" data-case="reject">Rechazar con motivo</button>`;}else if(currentCase.status==="Pendiente de subsanación"){actions=`<button class="btn primary" data-case="resubmitted">Registrar documentación corregida</button><button class="btn ghost" data-case="reject">Rechazar con motivo</button>`;}else if(currentCase.status==="Subsanada — pendiente de revisión"){actions=`<button class="btn primary" data-case="accept">Aceptar solicitud</button><button class="btn ghost" data-case="reject">Rechazar con motivo</button>`;}box.innerHTML=`<article class="event-card"><span class="event-meta">EXPEDIENTE · ${esc(currentCase.requestDate)}</span><h4>${esc(currentCase.name)}</h4><div class="case-grid"><div class="case-field"><span>Edad declarada</span><strong>${currentCase.age} años</strong></div><div class="case-field"><span>Año de nacimiento</span><strong>${currentCase.birthYear}</strong></div><div class="case-field"><span>Contacto</span><strong>${esc(currentCase.contact)}</strong></div><div class="case-field"><span>Estado</span><strong>${esc(currentCase.status)}</strong></div></div><p><strong>Observación del expediente:</strong> ${esc(currentCase.issue)}</p><p class="muted">Las fichas completas pueden aceptarse directamente. Si falta algo, puedes solicitar subsanación y volver a revisar la documentación corregida.</p><div class="event-actions">${actions}</div></article>`;}
  function handleCase(action){if(!currentCase)return;const c=currentCase;let msg="";if(action==="resubmitted"){if(c.status!=="Pendiente de subsanación")return;c.issue="La documentación corregida está completa y los datos coinciden.";c.status="Subsanada — pendiente de revisión";log("Documentación subsanada por "+c.name+".");save();renderAll();toast("Documentación recibida. Ya puedes revisar la ficha.");return;}if(action==="accept"){if(!["Pendiente","Subsanada — pendiente de revisión"].includes(c.status)){toast("Este expediente ya está resuelto.");return;}if(!/completa|corregida está completa/i.test(c.issue)){toast("Hay una incidencia: solicita subsanación antes de aceptar.");return;}if(state.brothers.some(b=>b.name===c.name)){toast("Esta persona ya figura en la lista de hermanos.");return;}state.brothers.push({name:c.name,role:"Hermano",status:"Activo",joinedAt:state.date});c.status="Aceptada";state.reputation=Math.min(100,state.reputation+1);msg="Solicitud aceptada: "+c.name;}else if(action==="fix"){if(c.status!=="Pendiente")return;c.status="Pendiente de subsanación";msg="Se ha solicitado corregir la documentación de "+c.name;}else if(action==="reject"){openModal(`<h3>Motivo del rechazo</h3><p>Indica el motivo para registrar la decisión.</p><textarea id="motivo-rechazo" rows="3" maxlength="250" placeholder="Motivo del rechazo"></textarea><div class="event-actions"><button class="btn primary" id="confirmar-rechazo">Confirmar rechazo</button></div>`);$("confirmar-rechazo").onclick=()=>{const reason=$("motivo-rechazo").value.trim();if(!reason){toast("Escribe un motivo antes de confirmar.");return;}c.status="Rechazada";c.reason=reason;state.reputation=Math.max(0,state.reputation-1);log("Solicitud rechazada: "+c.name+" ("+reason+")");currentCase=null;closeModal();save();renderAll();toast("Rechazo registrado.");};return;}log(msg);save();if(["Aceptada","Rechazada"].includes(c.status))currentCase=null;renderAll();toast(msg);}
  function renderBrothers(){
    const host=$("lista-hermanos");
    host.innerHTML=state.brothers.map(b=>`<div class="list-row"><strong>${esc(b.name)}</strong><small>${esc(b.role)} · ${esc(b.status)}</small></div>`).join("")||'<div class="empty">Todavía no hay hermanos censados.</div>';
    const campaigns=[
      {id:"redes",name:"Campaña en redes sociales",cost:180,desc:"Difusión digital y publicaciones durante varios días.",min:1,max:3,rep:1},
      {id:"puertas",name:"Jornada de puertas abiertas",cost:450,desc:"Visita a la casa hermandad, presentación de proyectos y convivencia.",min:2,max:5,rep:4},
      {id:"juvenil",name:"Captación juvenil y familiar",cost:320,desc:"Actividad para acercar a jóvenes y familias a la hermandad.",min:1,max:4,rep:3},
      {id:"caridad",name:"Acción solidaria en el barrio",cost:600,desc:"Colaboración vecinal que puede atraer nuevos hermanos y mejorar la imagen pública.",min:2,max:6,rep:7},
      {id:"boca",name:"Invitar a conocidos",cost:100,desc:"Pequeña campaña de invitación personal. Tiene coste, tiempo de espera y límite anual.",min:0,max:1,rep:0}
    ];
    let box=$("captacion-hermanos");
    if(!box){box=document.createElement("div");box.id="captacion-hermanos";host.parentElement.insertBefore(box,host);}
    const uses=Array.isArray(state.campaignUses)?state.campaignUses:[];
    const bocaUses=uses.filter(u=>u.id==="boca");
    const year=new Date(state.date).getFullYear();
    const usedThisYear=bocaUses.filter(u=>new Date(u.date).getFullYear()===year).length;
    const lastBoca=bocaUses.length?new Date(bocaUses[bocaUses.length-1].date):null;
    const daysSince=lastBoca?Math.floor((new Date(state.date)-lastBoca)/86400000):9999;
    const cooldownLeft=Math.max(0,60-daysSince);
    const bocaBlocked=cooldownLeft>0||usedThisYear>=3;
    box.innerHTML=`<h4>Captación de nuevos hermanos</h4><p class="muted">Invierte en actividades para atraer personas. Los resultados dependen de la reputación y son variables.</p><div class="campaign-grid">${campaigns.map(c=>{const blocked=c.id==="boca"&&bocaBlocked;const status=c.id==="boca"?(usedThisYear>=3?`Límite anual alcanzado (${usedThisYear}/3)`:cooldownLeft>0?`Disponible dentro de ${cooldownLeft} días · ${usedThisYear}/3 este año`:`Disponible · ${usedThisYear}/3 este año`):"";return `<article class="shop-card"><h4>${c.name}</h4><p>${c.desc}</p><p>Coste: <strong>${money(c.cost)}</strong> · Posibles altas: ${c.min}–${c.max}</p>${status?`<p class="muted">${status}</p>`:""}<button class="btn primary" data-campaign="${c.id}" ${blocked?"disabled":""}>${blocked?"No disponible":"Organizar campaña"}</button></article>`;}).join("")}</div>`;
    renderRequest();
  }
  function runCampaign(id){
    const campaigns={redes:{name:"Campaña en redes sociales",cost:180,min:1,max:3,rep:1},puertas:{name:"Jornada de puertas abiertas",cost:450,min:2,max:5,rep:4},juvenil:{name:"Captación juvenil y familiar",cost:320,min:1,max:4,rep:3},caridad:{name:"Acción solidaria en el barrio",cost:600,min:2,max:6,rep:7},boca:{name:"Invitar a conocidos",cost:100,min:0,max:1,rep:0}};
    const c=campaigns[id];if(!c)return;
    if(!Array.isArray(state.campaignUses))state.campaignUses=[];
    if(id==="boca"){
      const now=new Date(state.date),year=now.getFullYear();
      const uses=state.campaignUses.filter(u=>u.id==="boca");
      const usedThisYear=uses.filter(u=>new Date(u.date).getFullYear()===year).length;
      const last=uses.length?new Date(uses[uses.length-1].date):null;
      const daysSince=last?Math.floor((now-last)/86400000):9999;
      if(usedThisYear>=3){toast("Has alcanzado el límite de 3 campañas de invitación por año.");return;}
      if(daysSince<60){toast(`Debes esperar ${60-daysSince} días para volver a invitar a conocidos.`);return;}
    }
    if(state.balance<c.cost){toast("No hay saldo suficiente para organizar esta campaña.");return;}
    if(id==="boca")state.campaignUses.push({id,date:state.date});
    if(c.cost)addTransaction(c.name,-c.cost,"gasto");
    const reputationFactor=state.reputation>=80?1.25:state.reputation<35?0.65:1;
    const gained=Math.max(0,Math.round((c.min+Math.floor(Math.random()*(c.max-c.min+1)))*reputationFactor));
    const firstNames=["Álvaro","Lucía","Daniel","Carmen","Pablo","Marta","Alejandro","Rocío","Manuel","Inés","Javier","María","Adrián","Claudia","Antonio","Elena","Francisco","Lola","José","Ana"];
    const surnames=["García","Rodríguez","Fernández","López","Martín","Pérez","Sánchez","Romero","Torres","Moreno","Jiménez","Ruiz"];
    for(let i=0;i<gained;i++){let name;do{name=firstNames[Math.floor(Math.random()*firstNames.length)]+" "+surnames[Math.floor(Math.random()*surnames.length)];}while(state.brothers.some(b=>b.name===name));state.brothers.push({name,role:"Hermano",status:"Activo",joinedAt:state.date,joinedBy:c.name});}
    state.reputation=Math.max(0,Math.min(100,state.reputation+c.rep));
    log(`${c.name}: ${gained} nuevas altas. Gasto: ${money(c.cost)}.`);save();renderAll();toast(`Campaña finalizada: ${gained} nuevos hermanos.`);
  }
  function processMonthlyEconomy(d){
    const monthKey=`${d.getFullYear()}-${d.getMonth()+1}`;if(state.lastEconomyMonth===monthKey)return null;state.lastEconomyMonth=monthKey;
    const previousMonth=new Date(d.getFullYear(),d.getMonth()-1,1,12);const py=previousMonth.getFullYear(),pm=previousMonth.getMonth();
    const inPrevMonth=value=>{const dt=new Date(value);return Number.isFinite(dt.getTime())&&dt.getFullYear()===py&&dt.getMonth()===pm;};
    const previousTransactions=state.transactions.filter(t=>inPrevMonth(t.date)&&!/saldo inicial|tesorería inicial/i.test(t.concept||""));const income=previousTransactions.filter(t=>t.amount>0).reduce((a,t)=>a+t.amount,0);const expenses=previousTransactions.filter(t=>t.amount<0).reduce((a,t)=>a+Math.abs(t.amount),0);const newBrothers=state.brothers.filter(b=>b.joinedAt&&inPrevMonth(b.joinedAt)).map(b=>b.name);
    const activities=state.activity.filter(a=>a&&typeof a==="object"&&inPrevMonth(a.date)).slice(0,6).map(a=>a.text);const monthName=new Intl.DateTimeFormat("es-ES",{month:"long",year:"numeric"}).format(previousMonth);const report={monthKey:`${py}-${pm+1}`,monthName:monthName.charAt(0).toUpperCase()+monthName.slice(1),income,expenses,net:income-expenses,newBrothers,activities};
    const active=state.brothers.filter(b=>/activ[oa]/i.test(b.status||"")).length;
    const quotas=active*18;
    const upkeep=state.inventory.reduce((sum,item)=>sum+Math.min(60,Math.max(3,Math.round((Number(item.price)||0)*0.001))),0);
    const churchCost=state.church&&state.church.owned?650:0;
    const houseCost=state.house?(state.house.type==="rented"?700:({0:0,1:350,2:750,3:1250}[Number(state.house.level)||0]||0)):0;
    let operating=250+upkeep+churchCost+houseCost;if(state.difficulty==="tranquila")operating=Math.round(operating*.9);if(state.difficulty==="exigente")operating=Math.round(operating*1.15);
    if(quotas)addTransaction(`Cuotas mensuales (${active} hermanos)`,quotas,"ingreso");
    const community=120+active*8+Math.round(state.reputation*1.3);addTransaction("Donativos y colaboración del barrio",community,"ingreso");
    addTransaction("Gastos ordinarios, conservación y sedes",-operating,"gasto");
    const churchValues={"iglesia-historica":65000,capilla:150000,basilica:350000};const houseValues={small:45000,medium:95000,large:185000};
    const ownedValue=(state.church&&state.church.owned?(churchValues[state.church.type]||0):0)+(state.house&&state.house.type!=="rented"?(houseValues[state.house.type]||0):0);const propertySupport=Math.round(ownedValue*0.003);if(propertySupport>0)addTransaction("Donativos vinculados al patrimonio",propertySupport,"ingreso");
    if(state.reputation<30){state.reputation=Math.max(0,state.reputation-1);log("La reputación baja dificulta la colaboración de la feligresía.");}
    log(`Cierre mensual: cuotas ${money(quotas)}, donativos ${money(community+propertySupport)} y gastos ${money(operating)}.`);
    const monthIndex=d.getFullYear()*12+d.getMonth();if(typeof state.lastElectionMonth!=="number")state.lastElectionMonth=monthIndex;if(monthIndex-state.lastElectionMonth>=6)state.electionDue=true;
    report.economy={quotas,community,operating,propertySupport};state.lastMonthlyReportKey=report.monthKey;return report;
  }
  function renderShop(){const cat=$("filtro-categoria").value;const tier=$("filtro-nivel")?.value||"Todos";const list=products.filter(p=>(cat==="Todas"||p.category===cat)&&(tier==="Todos"||p.tier===tier)&&!state.inventory.some(i=>i.id===p.id));$("catalogo-tienda").innerHTML=list.map(p=>`<article class="shop-card"><div class="product-art" aria-hidden="true">${p.icon}</div><span class="event-meta">${esc(p.category)} · ${esc(p.tier)} · Calidad ${p.quality}/100</span><h4>${esc(p.name)}</h4><p>${esc(p.desc)}</p><div class="price">${money(p.price)}</div><div class="card-actions"><button class="btn primary" data-buy="${p.id}">Comprar</button><button class="btn secondary" data-details="${p.id}">Detalles</button></div></article>`).join("")||'<div class="empty">No hay artículos en esta categoría pendientes de compra.</div>';}
  function buyProduct(id){const p=products.find(x=>x.id===id);if(!p)return;if(state.balance<p.price){toast("No hay saldo suficiente para comprar este artículo.");return;}openModal(`<h3>Confirmar compra</h3><div class="product-art">${p.icon}</div><p>¿Quieres comprar <strong>${esc(p.name)}</strong> por <strong>${money(p.price)}</strong>?</p><p class="muted">El importe se descontará de la tesorería y el artículo pasará al inventario.</p><div class="event-actions"><button class="btn primary" id="confirmar-compra">Confirmar compra</button><button class="btn secondary" id="cancelar-compra">Cancelar</button></div>`);$("confirmar-compra").onclick=()=>{if(state.balance<p.price){closeModal();toast("Saldo insuficiente.");return;}addTransaction("Compra: "+p.name,-p.price,"gasto");state.inventory.push({...p,condition:p.quality,bought:dateText(new Date(state.date))});log("Comprado: "+p.name);save();closeModal();renderAll();toast("Artículo añadido al patrimonio.");};$("cancelar-compra").onclick=closeModal;}
  function renderInventory(){$("inventario").innerHTML=state.inventory.map(i=>`<article class="shop-card"><div class="product-art">${i.icon||"🏵️"}</div><span class="event-meta">${esc(i.category||"Patrimonio")}</span><h4>${esc(i.name)}</h4><p>Adquirido: ${esc(i.bought||"Sin fecha registrada")}</p><p>Conservación: <strong class="${i.condition<45?"danger":i.condition>75?"success":""}">${i.condition}%</strong></p><p>Calidad: ${i.quality||70}/100</p><div class="card-actions"><button class="btn secondary" data-inspect="${i.id}">Inspeccionar</button><button class="btn primary" data-maintain="${i.id}">Mantener (25 €)</button></div></article>`).join("")||'<div class="empty">El inventario está vacío.</div>';}
  function maintain(id){const item=state.inventory.find(i=>i.id===id);if(!item)return;if(state.balance<25){toast("No hay saldo suficiente para el mantenimiento.");return;}addTransaction("Mantenimiento: "+item.name,-25,"gasto");item.condition=Math.min(100,item.condition+18);log("Mantenimiento realizado: "+item.name);save();renderAll();toast("El estado de conservación ha mejorado.");}
  function renderCleanGame(){if(!cleanTask){const item=state.inventory[Math.floor(Math.random()*state.inventory.length)];cleanTask={id:item?.id||null,step:0,score:0,tool:null};}const item=state.inventory.find(i=>i.id===cleanTask.id);if(!item){$("minijuego-limpieza").innerHTML='<p>No hay enseres disponibles. Compra o añade patrimonio para empezar.</p>';return;}const steps=[{q:"¿Qué debes hacer antes de limpiar?",opts:["Inspeccionar el material y el estado","Aplicar el producto más fuerte","Frotar sin revisar"],good:0,tip:"La inspección ayuda a evitar daños."},{q:"¿Qué procedimiento es más prudente para un metal delicado?",opts:["Producto específico y paño suave","Estropajo abrasivo","Empaparlo y dejarlo secar solo"],good:0,tip:"Usa productos adecuados al material."},{q:"Al terminar, ¿qué debes hacer?",opts:["Secar, revisar y registrar el estado","Guardar el enser húmedo","No comprobar el resultado"],good:0,tip:"El secado y la revisión previenen deterioros."}];const s=steps[cleanTask.step];$("minijuego-limpieza").innerHTML=`<div class="product-art">${item.icon||"🕯️"}</div><span class="event-meta">ACTIVIDAD ${cleanTask.step+1} DE ${steps.length}</span><h4>${esc(item.name)}</h4><p>Estado actual: ${item.condition}% de conservación</p><h4>${s.q}</h4><div class="event-actions">${s.opts.map((o,i)=>`<button class="btn secondary" data-clean="${i}">${esc(o)}</button>`).join("")}</div><p class="muted">Cada decisión afecta al resultado de la actividad.</p>`;}
  function cleanAnswer(n){const steps=[{good:0,tip:"La inspección ayuda a evitar daños."},{good:0,tip:"Usa productos adecuados al material."},{good:0,tip:"El secado y la revisión previenen deterioros."}];if(n===steps[cleanTask.step].good)cleanTask.score+=1;else cleanTask.score-=1;cleanTask.step++;if(cleanTask.step>=steps.length){const item=state.inventory.find(i=>i.id===cleanTask.id);if(item){if(cleanTask.score>=2){item.condition=Math.min(100,item.condition+12);state.reputation=Math.min(100,state.reputation+2);log("Limpieza correcta de "+item.name);}else{item.condition=Math.max(0,item.condition-8);log("La limpieza de "+item.name+" requiere repetir la tarea.");} }const score=cleanTask.score;cleanTask=null;save();renderAll();openModal(`<h3>Actividad finalizada</h3><p>Resultado: <strong>${score>=2?"Buen trabajo":score===1?"Resultado mejorable":"Necesita más cuidado"}</strong></p><p>${score>=2?"El enser ha mejorado su conservación.":"El estado del enser se ha resentido. Revisa los procedimientos antes de intentarlo de nuevo."}</p><button class="btn primary" id="fin-limpieza">Volver a priostía</button>`);$("fin-limpieza").onclick=closeModal;}else{renderCleanGame();}}
  function renderTreasury(){$("historial-economico").innerHTML=state.transactions.slice(0,30).map(t=>`<div class="list-row"><strong>${esc(t.concept)}</strong><small>${esc(dateText(new Date(t.date)))} · ${t.type==="ingreso"?'<span class="success">+':''}${money(t.amount)}${t.type==="ingreso"?"</span>":""}</small></div>`).join("")||'<div class="empty">Todavía no hay movimientos.</div>';}
  function makeCalendar(){const d=new Date(state.date),p=phase(d);const base=[{name:"Revisión de inventario",kind:"Priostía"},{name:"Reunión de junta",kind:"Gobierno"},{name:"Revisión de cuotas",kind:"Secretaría"}];const pool=activities.filter(a=>p.cuaresma?a.season==="cuaresma":true);const chosen=[...pool].sort(()=>Math.random()-.5).slice(0,4);state.calendar=chosen.map((a,i)=>({name:a.name,kind:a.kind,date:dateText(new Date(d.getTime()+i*86400000)),cost:a.cost,rep:a.rep,done:false}));}
  function renderSedes(){
    if(!state.church)state.church={name:"Iglesia asignada",type:"assigned",owned:false};
    if(!state.house)state.house={type:"none",name:"Sin casa hermandad",level:0};
    if(!state.procession)state.procession={route:"Iglesia de salida → calles del barrio → plaza principal → regreso a la iglesia",stops:"",startTime:"16:00",returnTime:"01:00",distance:6,plannedYear:null,planned:false};
    const ch=state.church, h=state.house, p=state.procession, year=new Date(state.date).getFullYear(), cuaresma=phase(new Date(state.date)).cuaresma;
    const churches=[{id:"parroquia",name:"Parroquia del barrio",cost:0,desc:"Sede inicial cedida; sin coste de compra."},{id:"iglesia-historica",name:"Iglesia histórica",cost:65000,desc:"Templo histórico con inversión y conservación elevadas."},{id:"capilla",name:"Capilla propia",cost:150000,desc:"Capilla propia; inversión patrimonial importante."},{id:"basilica",name:"Basílica propia",cost:350000,desc:"Gran proyecto de construcción y mantenimiento."}];
    const houses=[{id:"none",name:"Sin casa hermandad",cost:0,level:0},{id:"rented",name:"Casa alquilada (700 €/mes)",cost:2500,level:1},{id:"small",name:"Casa hermandad pequeña",cost:45000,level:1},{id:"medium",name:"Casa hermandad mediana",cost:95000,level:2},{id:"large",name:"Casa hermandad amplia",cost:185000,level:3}];
    $("gestion-sedes").innerHTML=`<div class="two-col"><article class="panel"><h4>Sede canónica</h4><p>Actual: <strong>${esc(ch.name)}</strong>${ch.owned?" · Propiedad de la hermandad":""}</p><p class="muted">Cambiar de iglesia o construir una sede propia cuesta dinero. El traslado de sede cuesta además 1.000 € de gestiones.</p><div class="form-grid"><label>Elegir sede<select id="elegir-iglesia">${churches.map(c=>`<option value="${c.id}" ${ch.type===c.id?"selected":""}>${esc(c.name)} — ${money(c.cost)}</option>`).join("")}</select></label><button class="btn primary" data-sede="iglesia">Cambiar / adquirir sede</button></div></article><article class="panel"><h4>Casa hermandad</h4><p>Actual: <strong>${esc(h.name)}</strong></p><p class="muted">Una casa propia facilita la organización, pero aumenta los gastos mensuales. Puedes cambiarla o ampliarla más adelante.</p><div class="form-grid"><label>Elegir casa<select id="elegir-casa">${houses.map(x=>`<option value="${x.id}" ${h.type===x.id?"selected":""}>${esc(x.name)} — ${money(x.cost)}</option>`).join("")}</select></label><button class="btn primary" data-sede="casa">Alquilar / construir / cambiar</button></div></article></div><div class="season-card"><strong>Costes mensuales estimados</strong><p>Iglesia: ${money(ch.owned?650:0)} · Casa hermandad: ${money(h.type==="rented"?700:({0:0,1:350,2:750,3:1250}[h.level]||0))}. Se descontarán en el cierre de cada mes.</p></div>`;
    const bandOptions=[{id:"none",name:"Sin banda",rate:0},{id:"agrupacion",name:"Agrupación musical",rate:450},{id:"cornetas",name:"Banda de cornetas y tambores",rate:500},{id:"musica",name:"Banda de música",rate:550}];
    if(!p.band)p.band="agrupacion";const selectedBand=bandOptions.find(b=>b.id===p.band)||bandOptions[1];
    const hours=processionHours(p.startTime||"16:00",p.returnTime||"01:00");const bandTotal=Math.ceil(hours*selectedBand.rate);const routePoints=Array.isArray(p.points)?p.points:[];
    $("plan-estacion").innerHTML=`<h4>Planificación de la estación de penitencia</h4><p class="muted">${cuaresma?"Estamos en Cuaresma: puedes dibujar y confirmar la salida de este año.":"La planificación se abre durante la Cuaresma. Puedes consultar el último recorrido, pero no modificarlo fuera de ese periodo."}</p><div class="stats-grid"><div class="stat-card"><span>Salida</span><strong>${esc(p.startTime||"16:00")}</strong></div><div class="stat-card"><span>Regreso previsto</span><strong>${esc(p.returnTime||"01:00")}</strong></div><div class="stat-card"><span>Distancia estimada</span><strong>${Number(p.distance)||6} km</strong></div><div class="stat-card"><span>Plan del año</span><strong>${p.planned&&p.plannedYear===year?"Confirmado":"Pendiente"}</strong></div></div>
    <div class="map-instructions"><strong>Recorrido sobre mapa real</strong><p>Haz clic en el mapa para añadir puntos al recorrido en orden. La línea une los puntos que marques; puedes borrar el trazado y empezar de nuevo. Necesita conexión a Internet para cargar el mapa.</p><div class="map-actions"><button class="btn secondary" type="button" id="limpiar-trazado" ${cuaresma?"":"disabled"}>Borrar trazado</button><span id="puntos-trazado">${routePoints.length} puntos marcados</span></div></div><div id="mapa-estacion" class="procession-map" aria-label="Mapa interactivo para dibujar el recorrido"></div>
    <form id="form-estacion" class="form-grid"><label>Recorrido / calles (se genera con los puntos del mapa, también puedes corregirlo)<textarea id="recorrido-estacion" rows="3" maxlength="1200" required ${cuaresma?"":"disabled"}>${esc(p.route||"")}</textarea></label><label>Paradas o puntos de interés<textarea id="paradas-estacion" rows="2" maxlength="600" placeholder="Ej. Plaza principal; capilla del barrio" ${cuaresma?"":"disabled"}>${esc(p.stops||"")}</textarea></label><label>Hora de salida<input id="hora-salida" type="time" value="${esc(p.startTime||"16:00")}" required ${cuaresma?"":"disabled"}></label><label>Hora prevista de regreso<input id="hora-regreso" type="time" value="${esc(p.returnTime||"01:00")}" required ${cuaresma?"":"disabled"}></label><label>Distancia aproximada (km)<input id="distancia-estacion" type="number" min="1" max="50" step="0.1" value="${Number(p.distance)||6}" required ${cuaresma?"":"disabled"}></label><label>Banda contratada<select id="banda-estacion" ${cuaresma?"":"disabled"}>${bandOptions.map(b=>`<option value="${b.id}" ${b.id===p.band?"selected":""}>${b.name} — ${b.rate?money(b.rate)+"/hora":"sin coste"}</option>`).join("")}</select></label><div class="season-card band-estimate"><strong>Estimación de banda</strong><p id="estimacion-banda">Duración estimada: ${hours.toFixed(1)} h · Coste de banda: ${money(bandTotal)} · Gestión: ${money(250)} · Total: ${money(bandTotal+250)}</p><small>El coste se calcula según las horas entre la salida y el regreso, contando el regreso al día siguiente cuando corresponda.</small></div><button class="btn primary" type="submit" ${cuaresma?"":"disabled"}>Guardar y confirmar recorrido</button></form><p class="muted">La iglesia actual es el punto de salida y regreso. Los puntos del mapa se guardan en la partida. El trazado es manual y no sigue automáticamente cada calle.</p>`;
    initProcessionMap(routePoints,cuaresma);
    const updateBand=()=>{const h=processionHours($("hora-salida").value,$("hora-regreso").value);const b=bandOptions.find(x=>x.id===$("banda-estacion").value)||bandOptions[0];$("estimacion-banda").textContent=`Duración estimada: ${h.toFixed(1)} h · Coste de banda: ${money(Math.ceil(h*b.rate))} · Gestión: ${money(250)} · Total: ${money(Math.ceil(h*b.rate)+250)}`;};
    $("hora-salida").addEventListener("change",updateBand);$("hora-regreso").addEventListener("change",updateBand);$("banda-estacion").addEventListener("change",updateBand);
  }
  function changeSede(kind){
    if(kind==="iglesia"){
      const catalog={parroquia:{name:"Parroquia del barrio",cost:0,owned:false},"iglesia-historica":{name:"Iglesia histórica",cost:65000,owned:true},capilla:{name:"Capilla propia",cost:150000,owned:true},basilica:{name:"Basílica propia",cost:350000,owned:true}};
      const next=catalog[$("elegir-iglesia").value];if(!next)return;if(state.church.type===Object.keys(catalog).find(k=>catalog[k].name===next.name)){toast("La sede seleccionada ya es la actual.");return;}
      const total=next.cost+(state.church.name!=="Iglesia asignada"&&state.church.type!=="parroquia"?1000:0);if(state.balance<total){toast("No hay saldo suficiente para este cambio de sede.");return;}
      if(total)addTransaction("Adquisición / traslado de sede: "+next.name,-total,"gasto");state.church={...next,type:$("elegir-iglesia").value};log("La sede canónica pasa a ser "+next.name+".");
    } else {
      const catalog={none:{name:"Sin casa hermandad",cost:0,level:0},rented:{name:"Casa alquilada",cost:2500,level:1},small:{name:"Casa hermandad pequeña",cost:45000,level:1},medium:{name:"Casa hermandad mediana",cost:95000,level:2},large:{name:"Casa hermandad amplia",cost:185000,level:3}};
      const next=catalog[$("elegir-casa").value];if(!next)return;if(state.house.type===Object.keys(catalog).find(k=>catalog[k].name===next.name)){toast("Esa opción ya está seleccionada.");return;}if(state.balance<next.cost){toast("No hay saldo suficiente para esta casa hermandad.");return;}if(next.cost)addTransaction(($("elegir-casa").value==="rented"?"Alquiler de casa hermandad: ":"Construcción / cambio de casa hermandad: ")+next.name,-next.cost,"gasto");state.house={...next,type:$("elegir-casa").value};log("Casa hermandad actualizada: "+next.name+".");
    }
    save();renderAll();section("sedes");toast("Cambios de sede guardados.");
  }
  function processionHours(start,end){const a=String(start||"16:00").split(":").map(Number),b=String(end||"01:00").split(":").map(Number);let mins=(b[0]*60+b[1])-(a[0]*60+a[1]);if(mins<=0)mins+=1440;return Math.max(1,mins/60);}
  function initProcessionMap(points,editable){
    const el=$("mapa-estacion");if(!el||!window.L)return;
    if(window.__cofradeMap){try{window.__cofradeMap.remove();}catch(_){}}
    const map=L.map(el,{zoomControl:false}).setView([37.3891,-5.9845],14);window.__cofradeMap=map;
    L.control.zoom({position:"bottomleft"}).addTo(map);
    const baseTiles=L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png?key=cb1_4f9p_1_4429bace3ac31d727aa2fbf8",{maxZoom:19,subdomains:"abcd",attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> · © <a href="https://carto.com/attributions" target="_blank" rel="noopener">CARTO</a>',crossOrigin:true});
    baseTiles.on("tileerror",()=>{if(!map.__cofradeFallback){map.__cofradeFallback=true;try{map.removeLayer(baseTiles);}catch(_){};const fallback=L.tileLayer("https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png?key=cb1_4f9p_1_4429bace3ac31d727aa2fbf8",{maxZoom:19,subdomains:"abc",attribution:'© OpenStreetMap · © CARTO',crossOrigin:true}).addTo(map);fallback.on('tileerror',()=>{if(!map.__cofradeTilesErrorShown){map.__cofradeTilesErrorShown=true;toast("No se han podido cargar los mapas. Comprueba tu conexión a Internet.");}});}});
    baseTiles.addTo(map);
    const landmarkIcon=(symbol,kind)=>L.divIcon({className:`cofrade-map-icon landmark-${kind}`,html:`<span>${symbol}</span>`,iconSize:[30,30],iconAnchor:[15,15]});
    const landmarks=[
      {p:[37.3861,-5.9928],n:"Catedral de Sevilla",s:"✚",k:"church"},
      {p:[37.3893,-5.9940],n:"Iglesia del Salvador",s:"♜",k:"church"},
      {p:[37.3963,-5.9965],n:"Basílica de la Macarena",s:"✚",k:"church"},
      {p:[37.3927,-5.9990],n:"Museo de Bellas Artes",s:"▤",k:"public"},
      {p:[37.3880,-5.9956],n:"Ayuntamiento",s:"▦",k:"public"},
      {p:[37.3897,-5.9845],n:"Plaza Nueva",s:"♣",k:"park"},
      {p:[37.3858,-5.9910],n:"Archivo de Indias",s:"▤",k:"public"},
      {p:[37.3826,-5.9960],n:"Torre del Oro",s:"♜",k:"historic"},
      {p:[37.3912,-5.9868],n:"Plaza de San Francisco",s:"♣",k:"park"},
      {p:[37.3900,-5.9998],n:"Plaza del Duque",s:"♣",k:"park"}
    ];
    landmarks.forEach(x=>L.marker(x.p,{icon:landmarkIcon(x.s,x.k),interactive:true}).addTo(map).bindTooltip(x.n,{direction:"bottom",offset:[0,8],className:"cofrade-map-tooltip",opacity:.98}));
    let line=null;let markers=[];const pts=(points||[]).map(p=>[Number(p.lat),Number(p.lng)]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]));window.__cofradeRoutePoints=pts;
    const redraw=()=>{if(line)map.removeLayer(line);markers.forEach(m=>map.removeLayer(m));markers=[];if(pts.length){line=L.polyline(pts,{color:"#9b68ff",weight:5,opacity:.95,lineCap:"round",lineJoin:"round",dashArray:"1 0"}).addTo(map);pts.forEach((pt,i)=>{const icon=L.divIcon({className:"cofrade-route-icon",html:`<span>${i+1}</span>`,iconSize:[24,24],iconAnchor:[12,12]});markers.push(L.marker(pt,{icon,zIndexOffset:1000}).addTo(map).bindTooltip(i===0?"Salida · Punto 1":i===pts.length-1?`Regreso · Punto ${i+1}`:`Punto ${i+1}`,{className:"cofrade-map-tooltip"}));});if(pts.length>1)map.fitBounds(line.getBounds().pad(.15));else map.setView(pts[0],16);$("puntos-trazado").textContent=`${pts.length} puntos marcados`;const km=routeDistance(pts);if(km>0&&$("distancia-estacion"))$("distancia-estacion").value=Math.max(1,Math.round(km*10)/10);if($("recorrido-estacion")&&pts.length)$("recorrido-estacion").value="Recorrido dibujado sobre el mapa: "+pts.map((p,i)=>`${i+1}) ${p[0].toFixed(5)}, ${p[1].toFixed(5)}`).join(" → ");}else{$("puntos-trazado").textContent="0 puntos marcados";}};
    redraw();if(editable){map.on("click",e=>{pts.push([e.latlng.lat,e.latlng.lng]);window.__cofradeRoutePoints=pts;redraw();});$("limpiar-trazado").onclick=()=>{pts.splice(0,pts.length);window.__cofradeRoutePoints=pts;redraw();if($("recorrido-estacion"))$("recorrido-estacion").value="";if($("distancia-estacion"))$("distancia-estacion").value=6;};}
    setTimeout(()=>map.invalidateSize(),120);
  }
  function routeDistance(points){let total=0;for(let i=1;i<points.length;i++){const rad=x=>x*Math.PI/180;const [a,b]=points[i-1],[c,d]=points[i];const dl=rad(c-a),dn=rad(d-b),x=Math.sin(dl/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dn/2)**2;total+=6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}return total;}
  function saveProcession(e){e.preventDefault();if(!phase(new Date(state.date)).cuaresma){toast("La planificación de la estación se abre durante la Cuaresma.");return;}const route=$("recorrido-estacion").value.trim();if(route.length<10){toast("Dibuja el recorrido en el mapa o describe calles y plazas.");return;}const start=$("hora-salida").value,end=$("hora-regreso").value,band=$("banda-estacion").value;const rates={none:0,agrupacion:450,cornetas:500,musica:550};const hours=processionHours(start,end);const bandCost=Math.ceil(hours*(rates[band]||0));const total=250+bandCost;if(state.balance<total){toast(`No hay saldo suficiente. Necesitas ${money(total)} para gestión y banda.`);return;}addTransaction("Gestión y planificación de estación de penitencia",-250,"gasto");if(bandCost)addTransaction(`Contratación de banda (${hours.toFixed(1)} horas)`, -bandCost,"gasto");const points=window.__cofradeRoutePoints||[];state.procession={route,points:points.map(p=>({lat:p[0],lng:p[1]})),stops:$("paradas-estacion").value.trim(),startTime:start,returnTime:end,distance:Number($("distancia-estacion").value),band,bandCost,plannedYear:new Date(state.date).getFullYear(),planned:true};state.reputation=Math.min(100,state.reputation+1);log(`Estación de penitencia planificada para ${state.procession.plannedYear}. Banda: ${money(bandCost)} por ${hours.toFixed(1)} horas.`);save();renderAll();section("sedes");toast("Recorrido y presupuesto de estación guardados.");}
  function renderCalendar(){$("fase-liturgica").innerHTML=`<h4>${esc(phase(new Date(state.date)).name)}</h4><p>${esc(phase(new Date(state.date)).description)}</p><p>Semana Santa de ${new Date(state.date).getFullYear()}: Domingo de Ramos ${dateText(new Date(easterDate(new Date(state.date).getFullYear()).getTime()-7*86400000))}; Domingo de Resurrección ${dateText(easterDate(new Date(state.date).getFullYear()))}.</p>`;$("lista-calendario").innerHTML=state.calendar.map((a,i)=>`<div class="list-row"><strong>${esc(a.name)}</strong><small>${esc(a.date)} · ${esc(a.kind)}${a.done?" · Realizada":""}</small><div class="event-actions"><button class="btn secondary" data-activity="${i}" ${a.done?"disabled":""}>Realizar actividad${a.cost?` (${money(a.cost)})`:""}</button></div></div>`).join("")||'<div class="empty">No hay actividades programadas.</div>';}
  function doActivity(i){const a=state.calendar[i];if(!a||a.done)return;if(state.balance<a.cost){toast("No hay saldo suficiente para esta actividad.");return;}if(a.cost)addTransaction(a.name,-a.cost,"gasto");state.reputation=Math.min(100,state.reputation+a.rep);a.done=true;log("Actividad realizada: "+a.name);save();renderAll();toast("Actividad completada.");}
  function advanceDay(automatic=false){if(!state)return;const wasPlaying=!!state.playing;const d=new Date(state.date);d.setDate(d.getDate()+1);state.date=d.toISOString();state.dayCount++;let monthlyReport=null;if(d.getDate()===1)monthlyReport=processMonthlyEconomy(d);state.inventory.forEach(i=>{if(state.dayCount%7===0)i.condition=Math.max(0,i.condition-1);});makeCalendar();const p=phase(d);if(p.cuaresma)log("La hermandad se encuentra en Cuaresma: revisa los preparativos.");if(monthlyReport){resumePlaybackAfterModal=wasPlaying;stopPlayback();save();renderAll();showMonthlyReport(monthlyReport);return;}save();renderAll();if(Math.random()<(automatic?0.42:0.62)){generateEvent("auto");}else if(!automatic)toast("Has avanzado al "+dateText(d)+".");}
  function openModal(html){$("modal-contenido").innerHTML=html;$("modal").classList.remove("hidden");}
  function closeModal(resume=false){$("modal").classList.add("hidden");$("modal-contenido").innerHTML="";if(resume&&resumePlaybackAfterModal){const shouldResume=resumePlaybackAfterModal;resumePlaybackAfterModal=false;if(shouldResume&&state)startPlayback();}if(!state||!state.electionDue)currentMonthlyReport=null;}
  function renderSection(name){if(name==="sedes")renderSedes();if(name==="resumen")renderSummary();if(name==="eventos")renderEvents();if(name==="hermanos")renderBrothers();if(name==="tienda")renderShop();if(name==="patrimonio")renderInventory();if(name==="priostia")renderCleanGame();if(name==="tesoreria")renderTreasury();if(name==="calendario")renderCalendar();}
  function renderAll(){renderTop();renderSummary();renderEvents();renderBrothers();renderShop();renderInventory();renderTreasury();renderCalendar();renderSedes();if($("section-priostia").classList.contains("active"))renderCleanGame();}
  function startNew(config={}){stopPlayback();state=freshState();const modes={tranquila:18000,equilibrada:12000,exigente:7000};state.difficulty=config.difficulty||"equilibrada";state.balance=modes[state.difficulty]||12000;state.transactions=[{concept:"Tesorería inicial",amount:state.balance,type:"saldo",date:state.date}];state.gameName=config.name||"Hermandad del Consuelo";state.saveId="partida-"+Date.now()+"-"+Math.random().toString(36).slice(2,7);currentCase=null;cleanTask=null;resumePlaybackAfterModal=false;makeCalendar();showScreen("juego");save();renderAll();section("resumen");updatePlayButton();closeModal();toast("¡La hermandad ha sido fundada!");}
  function showNewGameOptions(){openModal(`<div class="create-hermandad"><span class="event-meta">NUEVA AVENTURA COFRADE</span><h3>Crea tu hermandad</h3><p>Elige cómo empezar. Puedes dejar que el juego lo decida todo o personalizar la identidad y la economía inicial.</p><div class="create-mode-card"><h4>Fundación aleatoria</h4><p>El juego genera un nombre y asigna una situación económica al azar.</p><button type="button" class="btn primary" data-create-mode="random">Crear hermandad aleatoria</button></div><div class="create-mode-card"><h4>Personalizar hermandad</h4><form id="form-crear-hermandad" class="create-form"><label>Nombre de la hermandad<input id="nombre-nueva-hermandad" required maxlength="70" value="Hermandad del Consuelo" placeholder="Hermandad de…"></label><label>Situación económica inicial<select id="dificultad-nueva-hermandad"><option value="tranquila">Desahogada · 18.000 € y menos gastos</option><option value="equilibrada" selected>Equilibrada · 12.000 €</option><option value="exigente">Exigente · 7.000 € y más gastos</option></select></label><button class="btn primary" type="submit">Fundar mi hermandad</button></form></div></div>`);const form=$("form-crear-hermandad");form.addEventListener("submit",e=>{e.preventDefault();const name=$("nombre-nueva-hermandad").value.trim();if(name.length<3){toast("Escribe un nombre de al menos 3 caracteres.");return;}startNew({name,difficulty:$("dificultad-nueva-hermandad").value});});}
  $("btn-nueva").addEventListener("click",showNewGameOptions);
  $("btn-guardar").addEventListener("click",()=>{save();toast("Partida guardada.");});
  $("btn-salir").addEventListener("click",()=>{stopPlayback();save();showScreen("inicio");});
  document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>section(b.dataset.section)));
  $("btn-avanzar-dia").addEventListener("click",()=>advanceDay(false));$("btn-avanzar-calendario").addEventListener("click",()=>advanceDay(false));$("btn-play").addEventListener("click",togglePlayback);
  $("plan-estacion").addEventListener("submit",e=>{if(e.target.id==="form-estacion")saveProcession(e);});
  $("btn-generar-evento").addEventListener("click",()=>{generateEvent("manual");renderAll();section("eventos");});
  $("btn-nueva-solicitud").addEventListener("click",()=>{makeRequest();section("hermanos");});
  $("filtro-categoria").addEventListener("change",renderShop);$("filtro-nivel")?.addEventListener("change",renderShop);
  $("form-movimiento").addEventListener("submit",e=>{e.preventDefault();const concept=$("concepto").value.trim(),amount=Number($("importe").value),type=$("tipo-movimiento").value;if(!concept||!Number.isFinite(amount)||amount<=0){toast("Introduce un concepto y un importe válido.");return;}const delta=type==="ingreso"?amount:-amount;if(delta<0&&state.balance<Math.abs(delta)){toast("No hay saldo suficiente para ese gasto.");return;}addTransaction(concept,delta,type);log((type==="ingreso"?"Ingreso: ":"Gasto: ")+concept);save();e.target.reset();renderAll();toast("Movimiento registrado.");});
  document.body.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.loadSave)loadSaveById(b.dataset.loadSave);if(b.dataset.deleteSave)deleteSaveById(b.dataset.deleteSave);if(b.dataset.event)resolveEvent(b.dataset.event,Number(b.dataset.choice));if(b.dataset.modalEvent){const id=b.dataset.modalEvent,choice=Number(b.dataset.modalChoice);closeModal();resolveEvent(id,choice);section("eventos");}if(b.dataset.monthlyClose!==undefined){closeModal(true);}if(b.dataset.electionCandidate){resolveElection(b.dataset.electionCandidate);}if(b.dataset.createMode==="random"){const names=["Hermandad de la Aurora","Hermandad del Consuelo","Hermandad de la Luz","Hermandad del Buen Camino","Hermandad de San Gabriel","Hermandad del Amparo","Hermandad de la Paz","Hermandad de la Esperanza del Barrio"];const difficulties=["tranquila","equilibrada","exigente"];startNew({name:names[Math.floor(Math.random()*names.length)],difficulty:difficulties[Math.floor(Math.random()*difficulties.length)]});}if(b.dataset.case)handleCase(b.dataset.case);if(b.dataset.buy)buyProduct(b.dataset.buy);if(b.dataset.details){const p=products.find(x=>x.id===b.dataset.details);if(p)openModal(`<div class="product-art">${p.icon}</div><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><p>Categoría: ${esc(p.category)}</p><p>Calidad: ${p.quality}/100</p><p class="price">${money(p.price)}</p>`);}if(b.dataset.inspect){const p=state.inventory.find(x=>x.id===b.dataset.inspect);if(p)openModal(`<div class="product-art">${p.icon||"🏵️"}</div><h3>${esc(p.name)}</h3><p>${esc(p.desc||"Bien inventariado en la hermandad.")}</p><p>Fecha de adquisición: ${esc(p.bought||"Sin fecha")}</p><p>Conservación: ${p.condition}%</p><p>Calidad: ${p.quality}/100</p>`);}if(b.dataset.campaign)runCampaign(b.dataset.campaign);if(b.dataset.sede)changeSede(b.dataset.sede);if(b.dataset.maintain)maintain(b.dataset.maintain);if(b.dataset.clean!==undefined)cleanAnswer(Number(b.dataset.clean));if(b.dataset.activity!==undefined)doActivity(Number(b.dataset.activity));});
  $("cerrar-modal").addEventListener("click",closeModal);$("modal").addEventListener("click",e=>{if(e.target===$("modal"))closeModal();});
  if("serviceWorker" in navigator && location.protocol!=="file:")window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
  migrateOldSave();
  renderSavedGames();
  updatePlayButton();
})();